services:
  provider-a:
    image: wiremock/wiremock:3.13.2
    ports:
      - "9101:8080"
    volumes:
      - ./provider-stubs/provider-a/mappings:/home/wiremock/mappings:ro
      - ./provider-stubs/provider-a/__files:/home/wiremock/__files:ro
    command:
      - --global-response-templating
      - --disable-gzip
      - --verbose
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s
    networks:
      - partner-bridge

  provider-b:
    image: wiremock/wiremock:3.13.2
    ports:
      - "9102:8080"
    volumes:
      - ./provider-stubs/provider-b/mappings:/home/wiremock/mappings:ro
      - ./provider-stubs/provider-b/__files:/home/wiremock/__files:ro
    command:
      - --global-response-templating
      - --disable-gzip
      - --verbose
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/health"]
      interval: 3s
      timeout: 2s
      retries: 15
      start_period: 5s
    networks:
      - partner-bridge

  payment-integration-service:
    build:
      context: ./services/payment-integration-service
    environment:
    # port mapping debug
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      SPRING_PROFILES_ACTIVE: gateway
      PARTNERBRIDGE_CLIENT_TRUSTED_IDENTITY_REQUIRED: "true"
      PARTNERBRIDGE_PROVIDER_A_BASE_URL: http://provider-a:8080
      PARTNERBRIDGE_PROVIDER_B_BASE_URL: http://provider-b:8080
    # port mapping debug
    ports:
      - "5005:5005"
    depends_on:
      provider-a:
        condition: service_healthy
      provider-b:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 20s
    networks:
      - partner-bridge

  kong:
    image: kong:3.9.3
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./gateways/kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "127.0.0.1:8001:8001"
    depends_on:
      payment-integration-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 15s
    networks:
      - partner-bridge

networks:
  partner-bridge:
    name: partner-bridge
